plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/jmccl/Story-Bell"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/0_3"
to = "/childrens-stories-ages-0-3"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/4_6"
to = "/childrens-stories-ages-4-6"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/7_12"
to = "/childrens-stories-ages-7-12"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/0_3.html"
to = "/childrens-stories-ages-0-3"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/4_6.html"
to = "/childrens-stories-ages-4-6"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/7_12.html"
to = "/childrens-stories-ages-7-12"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]